[((last_payer_changed_at) (can_apply . t) (can_join . :json-false) (is_commercial . t) (is_volunteer . :json-false) (is_manager . t) (approved . :json-false) (status . 1) (style . "") (banner_link) (banner_text . "") (banner_height) (banner) (commercial_from . "2016-12-15T06:32:57.000Z") (restricted_date) (restricted . :json-false) (parent_id . "brfmTWWPar5OkeacwqjQXA") (tabs_order . "---
- tickets
- team
- wiki
- stream
- files
- admin
- git
- messages
- custom_tab
- webhook
- ssh
- time
- standup
") (default_showpage . "Tickets") (updated_at . "2017-01-12T04:16:42.000Z") (created_at . "2016-12-15T06:32:57.000Z") (team_tab_role . 0) (share_permissions . t) (watcher_permissions . 1) (team_permissions . 2) (public_permissions . 0) (wiki_name . "test space") (description . "") (name . "Test Space") (id . "brs1F4WPar5OkeacwqjQXA")) ((last_payer_changed_at) (can_apply . t) (can_join . :json-false) (is_commercial . t) (is_volunteer . :json-false) (is_manager . t) (approved . :json-false) (status . 1) (style . "") (banner_link) (banner_text . "") (banner_height) (banner) (commercial_from . "2016-12-15T09:45:29.000Z") (restricted_date) (restricted . :json-false) (parent_id . "brfmTWWPar5OkeacwqjQXA") (tabs_order . "---
- tickets
- team
- wiki
- stream
- files
- admin
- messages
- standup
- support
- webhook
- time
- ssh
") (default_showpage . "Tickets") (updated_at . "2016-12-21T10:16:47.000Z") (created_at . "2016-12-15T09:45:29.000Z") (team_tab_role . 0) (share_permissions . t) (watcher_permissions . 1) (team_permissions . 2) (public_permissions . 0) (wiki_name . "test space-mobile") (description) (name . "Test Space Mobile") (id . "a2VBRsWQSr5P7dacwqEsg8")) ((last_payer_changed_at) (can_apply . t) (can_join . :json-false) (is_commercial . t) (is_volunteer . :json-false) (is_manager . t) (approved . :json-false) (status . 1) (style . "") (banner_link) (banner_text . "") (banner_height) (banner) (commercial_from . "2016-11-24T04:21:38.000Z") (restricted_date . "2017-01-12") (restricted . t) (parent_id . "b7yruYQU4r5OoAacwqEsg8") (tabs_order . "---
- summary
- tickets
- svn
- wiki
- stream
- files
- team
- admin
- messages
- ssh
- time
- support
- subprojects
- standup
") (default_showpage . "Summary") (updated_at . "2016-11-30T02:32:05.000Z") (created_at . "2016-11-24T04:21:38.000Z") (team_tab_role . 0) (share_permissions . t) (watcher_permissions . 1) (team_permissions . 2) (public_permissions . 0) (wiki_name . "skywalker-mobile-app") (description . "") (name . "Skywalker Mobile App") (id . "b-hOFUSF0r5QFddmr6bg7m"))]
